name: CI

on: 
  push:
    branches: main
    
  workflow_dispatch:
  
jobs:
  build: 
    runs-on: ubuntu-latest
    
    steps: 
      - uses: actions/checkuot@v3
      - name: Run one line skript
        run: echo Hello world Aika !! 
